[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neco_ping"
version = "0.1.0"
description = "Minimalistic Telegram notifier for ML pipelines nya"
dependencies = [
  "requests"
]

[tool.setuptools.packages.find]
where = ["src"]

